---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-secret
  namespace: traefik
spec:
  encryptedData:
    CF_API_EMAIL: AgDAIIkrcWBVTo3HhRMCPVCpfwDBRjzWHuqAsjcc5hQFsKeVOM+0KhG759/ojJxSQRCY+r3LXGxgNe2g+bezQyqJ4whEWzIO+mGEUSULGPTObrTmnARarD8L+yKCaBOhHkMY3o6sc1MQdd/f+LRC2xVXUqPDNCSyPqA0ywUzTFiujBbSQp7tamOvBjb7Djeni91LYQlklwTWqh4MtFeAp2w1XsKazIwNW5ZNa9o/LL/xeFbSY9CjmZZcjYQEnq/nXfrY8E0B0/gHa50TGG9ELI8w73j9koUaRAXP6zUMkzQCd/3voiowY3n1eSAmrfb9XbG4t9eAI+XDWnhKkmpCXe4JgfXiWEhqPfhm87F8wnNIZtl0gRLUOLx5eBvwm7GINT+jv98uZMUkgzawv1KkltWpxLxAhpEHgldeKXcOCfVtHD0oCahZqyEZeQ6HwlKBHY8mgjbE/VyXcfoNk3CJPTQuhNenEO/74iiawldMXAWGigkb1ierkyFb7xC4uVk5qCAy5V+WJPoCXfWHmZasJKJfkxo63Q3+M0zAHl6F1ubKllzxN19efQpsvK465FV+eap5ktxuYaum+AUr4IOervKb6VtcgeDRV04Ni+yz9gkwR8wd5XmbzKVWUM26i4IsNaoWZUeylTLtawkF5JSUonqtzKlZSR6TNnfhxoRDrBQO6vJiSJYhmySM+D20pr0DpWij0M5IpBDA0DodRJDKNqBIRXA25ixp
    CF_DNS_API_TOKEN: AgCNnMULi43Sjtpw0mGky7GpzVc9ov6ReWU4+OhR83ga8lSz1RezHHmmALi8qs4Dphgy+6K0wdoEQTCkg4PoyqmMuIW4ZstyiSOwkg5a/rvR0eAjJYYPVWA7JN5ggvx2OpG6rTuXcYgHTUDsFXKRNj55+fxAjHffWdurDTWbzc4VIHib161NTaJKkqyzuZIvddajFKaMRHLzoUa8Cvn0v23rKLBBWZpp9Ib34xdn9yVuafAiFzGvh5K0xM8j0iP/IjOOU9Fvwv6yVufhBvbTNvxw8tvlXIK4ldphuGH0VowxQqge2H8n1dBs6tcZv7QsTZm4FarEASnuq2nI4aijCDLDmdRVGw0J0ajIPQYxrTwpViJn2xEU243C4L/cs083jKMjnWYn44jeKnveObCi52pnltL8V7ujRKy85QTmoLb7rLeo33zIC+QuOihu7DBmXlMHXAwKLqY/zRw84yzIQZRQ11ZV3x8USZUwWNj1XSNcZqOb1ZniXSq0Huj4xVRh3wNGatov8hvRJoWrKdW7Xi+xX5efyxSvAH0Lxb3N9s/7OIWWTZIfMCx/wTDl8Ej5VonYI2meE/qbETZ2/ano0ULAukEYl39vRht+4+tooo0gXXpJxEhoEw2wHfIEkVcCepyX25lvcZfTIiKD/A2HoS4VgF4pMK9bs0Sa6juGFgwEbjjgfrruD2A0NUcssvic0Bvexei2ZybvjaVroewKjI+C/X9ptZvrTcmaoz/H+d4FkSQNBzUluyYN
  template:
    metadata:
      creationTimestamp: null
      name: traefik-secret
      namespace: traefik
